In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/drive/MyDrive/Cracks to craters - Ai internship project 2026 Ronak, Osh & Katyayani/Data/pothole-risk/pothole-risk.csv")

In [4]:
df.head()

,road_id,avg_rainfall_mm,traffic_volume_vph,pavement_age_yrs,soil_type,last_repair_yrs,pothole_risk_label
0,R001,820,4100,12,clay,3,High
1,R002,540,2100,6,gravel,2,Medium
2,R003,2450,6800,9,clay,4,High
3,R004,320,1400,3,sandy,1,Low
4,R005,1600,5000,14,clay,3,High

In [5]:
df.tail()

,road_id,avg_rainfall_mm,traffic_volume_vph,pavement_age_yrs,soil_type,last_repair_yrs,pothole_risk_label
245,R246,120,900,2,sandy,1,Low
246,R247,2100,5300,10,clay,2,High
247,R248,430,2800,5,gravel,3,Medium
248,R249,720,2200,7,clay,2,Medium
249,R250,90,1000,2,sandy,1,Low

In [6]:
df.isnull().sum()

road_id               0
avg_rainfall_mm       0
traffic_volume_vph    0
pavement_age_yrs      0
soil_type             0
last_repair_yrs       0
pothole_risk_label    0
dtype: int64

In [7]:
x = df.drop(["road_id", "pothole_risk_label"], axis = 1)
y = df["pothole_risk_label"]
x = pd.get_dummies(x, columns=["soil_type"]) # create new colu,ns on whether its a soil type, with boolean values

In [8]:
x.head()

,avg_rainfall_mm,traffic_volume_vph,pavement_age_yrs,last_repair_yrs,soil_type_clay,soil_type_gravel,soil_type_sandy
0,820,4100,12,3,True,False,False
1,540,2100,6,2,False,True,False
2,2450,6800,9,4,True,False,False
3,320,1400,3,1,False,False,True
4,1600,5000,14,3,True,False,False

In [9]:
y.head()

0      High
1    Medium
2      High
3       Low
4      High
Name: pothole_risk_label, dtype: object

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state = 42)

In [12]:
print(type(x_train))

<class 'pandas.core.frame.DataFrame'>

In [13]:
x_train.shape

(200, 7)

In [14]:
y_train.shape

(200,)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
model = LogisticRegression(max_iter=5000)

In [17]:
model.fit(x_train, y_train)

LogisticRegression(max_iter=5000)

In [18]:
y_pred = model.predict(x_test)

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
print(f"Accuracy score: {accuracy_score(y_test, y_pred)}")

Accuracy score: 0.94

In [24]:
features =  df.drop(["road_id", "pothole_risk_label"], axis = 1).columns.tolist()
print(features)

['avg_rainfall_mm', 'traffic_volume_vph', 'pavement_age_yrs', 'soil_type', 'last_repair_yrs']

In [28]:
user_input = []
user_input.append([input(f"{i}: ") for i in features])
prediction = model.predict(user_input)
print(prediction[0])

avg_rainfall_mm: 820
traffic_volume_vph: 4100
pavement_age_yrs: 12
soil_type: clay
last_repair_yrs: 5

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

ValueError: dtype='numeric' is not compatible with arrays of bytes/strings.Convert your data to numeric values explicitly instead.

In [21]:
import pickle

In [22]:
# saving the model
with open("pothole_risk_model.pkl", "wb") as f:
    pickle.dump(model, f)
with open("feature_columns.txt", "w") as f:
    f.write("\n".join(x_train.columns.tolist())) #separates column names line by line